# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='bind_hosts',
            field=models.ManyToManyField(to='source.BindHost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bind_host',
            field=models.ManyToManyField(to='source.BindHost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='host_group',
            field=models.ManyToManyField(to='source.HostGroup'),
        ),
    ]
