# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20181025_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindhost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
